package com.myspace.fyndna;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class broker implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer tcom;

	private java.lang.Integer commission;

	public broker() {
	}

	public java.lang.Integer getTcom() {
		return this.tcom;
	}

	public void setTcom(java.lang.Integer tcom) {
		this.tcom = tcom;
	}

	public java.lang.Integer getCommission() {
		return this.commission;
	}

	public void setCommission(java.lang.Integer commission) {
		this.commission = commission;
	}

	public broker(java.lang.Integer tcom, java.lang.Integer commission) {
		this.tcom = tcom;
		this.commission = commission;
	}

}